### ISSUE TITLE
[Fluent theme] Modified palette and theme colors are not present in the export

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#74]
**Describe the bug**
Creating a color modification to Fluent's palette or theme color variables is respected within ThemeBuilder, but the changes are not in the generated CSS files.

**To Reproduce**
1. Create a new Fluent theme
2. Change the color of any color variable like **--kendo-primary-100** or **--kendo-tertiary-100**. Observe the color changes as expected within the ThemeBuilder application
3. Export the modified theme and observe the generated CSS

**Actual Results**
The color variables are exported with their initial values. The new color values are not present in the generated CSS.

**Screenshots**
![image](https://github.com/telerik/themebuilder/assets/18008302/b2b12dd2-caeb-409e-aeb8-02c6f06d5659)

![image](https://github.com/telerik/themebuilder/assets/18008302/35c47f62-293d-42cb-8faa-a5443bb6e1d0)

**Components technology and version**
ThemeBuilder Q1 2024

**Additional context**
reported through t.1640628

**Comment by kvelikov** [comment]
This is the expected behavior - all custom styles and variables are exported at the end of the CSS file. All variables are prefixed with the --tb- prefix. Then the --kendo-* variables are linked to the custom ones: 

![Image](https://github.com/telerik/themebuilder/assets/5024892/c908203f-c4d1-4124-9764-97a20979292f)
