### ISSUE TITLE
Properties of nested component (parts) are not populated with the proper default value

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#79]
**Describe the bug**

**To Reproduce**
1. Create new Fluent theme
1. Open the **Button** component and select the **Focused** state.
1. Set a custom value for the **Effects** property. 
![image](https://github.com/telerik/themebuilder/assets/18008302/17a49d7d-60c4-4c30-9596-61d81a36f494)
1. Then go to the **DropDownTree** component, and select the **Button > Focused** template

Result: the Effect property is missing the pre-set value (through the Button template) and as a result, we are not presenting a none option (as by default TB assumes there is no value and there is not need to set none)

![image](https://github.com/telerik/themebuilder/assets/18008302/d89c6e21-0190-4242-9d51-9c580a110d0b)

**Expected behavior**
The property pane shows all pre-defined properties as set in the main component templates.

**Workaround**
To explicitly select the property, set another value,m and then explicitly set **none**

**Additional context**
Reported through t.1642053
Possibly related to https://github.com/telerik/theme-builder-pro/issues/2178

**Comment by imtodor** [comment]
The populated value comes from the 'Normal' state of the Button because the Button within the DropDownTree Button template states is always represented in the 'Normal' state. Furthermore, there are two ways to open the DropDownTree - click on the Input part and click on the Button part. However, when you open the DropDownTree by clicking on the button, you put it into its focused state in addition to the focused state of the parent DropDownTreeButton. That is the reason you are seeing the 'Focused' Button' styles. 

All of the above applies to the Button's 'Hover' state as well.
