### ISSUE TITLE
Styles set with !important in the Kendo theme are not overwritten by ThemeBuilder

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#81]
**Describe the bug**
Some styles are explicitly set with **!important** in the Kendo Themes. For example (for Default Blue)
![image](https://github.com/telerik/themebuilder/assets/18008302/8b531bfc-4d64-434c-8808-91733689b89c)

However we should be able to overwrite this style, but currently, the theme specificity is higher. As a result, some styles can't be properly set through ThemeBuilder

**To Reproduce**
1. Go to 'TabStrip' > `Active` > `Normal`
2. Scroll to the **Borders** property and try to set a color for the **bottom border**

**Actual Results**
The bottom border is still transparent, as the default theme styles are with higher specificity.

**Expected behavior**
To overwrite the `!important` 

**Screenshots**
![image](https://github.com/telerik/themebuilder/assets/18008302/28a16ca2-7b59-4635-9ace-84c8173fc4e5)

**Components technology and version**
If applicable and related to the Kendo/Telerik components - write the technology and component version

**Additional context**
Reported through t.1642457

**Comment by vstaykov** [comment]
ThemeBuilder successfully overwrites `!important` styles rules coming from Kendo theme.

The issue here comes from the Tabstrip templates structure. In details, the component supports several orientations that place the tabs list on different position (`top`, `bottom`, `left`, and `right`) and has the orientation corresponding class name (e.g. `k-tabstrip-top`).

The `Active Tab` template structure does not contain an orientation class so any customisations made do not include orientation specific class and can be applied in all orientations.

However, the border-bottom color rule example in this issue comes from **k-tabstrip-top** > .k-tabstrip-items-wrapper .k-item.kactive and is specific to the `top` orientation component. This is the reason it is not detected in the more generic `active tab` template.

We will introduce (in Q2 '24) templates available for customisation for the different Trabstrip orientations. Common styles and states can be customised for all orientations using the `Active Tab` templates. Styles for specific orientation can  be customisations using the new orientation specific templates.

**Comment by rkirilov** [comment]
Fixed in Q2 2024
